
apiVersion: morphling.kubedl.io/v1alpha1
kind: ProfilingExperiment
metadata:
  name: demo_model-v1.0.0-exp
spec:
  objective:
    type: maximize
    objectiveMetricName: qps
  algorithm:
    algorithmName: grid
  parallelism: 824644096132
  maxNumTrials: 824644096128
    tunableParameters:
    - category: "resource"
      parameters:
        - parameterType: discrete
          name: "CPU"
          feasibleSpace:
            list:
              - "500m"
              - "2000m"
    - category: "env"
      parameters:
        - parameterType: discrete
          name: "BATCH_SIZE"
          feasibleSpace:
            list:
              - "1"
              - "2"
              - "4"
              - "8"

  clientTemplate:
    spec:
      template:
        spec:
          containers:
          - name: client
            image: kubedl/morphling-grpc-client:demo
            resources:
              requests:
                cpu: 4
                memory: "4Gi"
              limits:
                cpu: 10
                memory: "10Gi"
            command: ["python3"]
            args: ["morphling_client.py"]
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
      backoffLimit: 10
  servicePodTemplate:
    template:
      spec:
        containers:
          - name: service-container
            image: kubedl/morphling-grpc-server:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: MODEL_NAME
                value: "demo_model"
            resources:
              requests:
                cpu: 10
                memory: "8Gi"
                nvidia.com/gpu: "1"
              limits:
                cpu: 20
                memory: "16Gi"
                nvidia.com/gpu: "1"
            ports:
              - containerPort: 8500
            volumeMounts:
              - name: model-cache
                mountPath: /workspace/.kubedl_model_cache
        volumes:
          - name: model-cache
            emptyDir: {}
        restartPolicy: Always
